# Generated by Django 5.0.4 on 2024-05-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_code',
            new_name='code',
        ),
    ]
