# Generated by Django 5.0.4 on 2024-05-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_alter_lecturer_code_alter_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='address',
            field=models.CharField(default='TP Hồ Chí Minh', max_length=100),
        ),
        migrations.AddField(
            model_name='ministry',
            name='birthday',
            field=models.DateField(default='2003-08-16'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='code',
            field=models.CharField(default='TPM', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='address',
            field=models.CharField(default='TP Hồ Chí Minh', max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='birthday',
            field=models.DateField(default='2003-08-16'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='code',
            field=models.CharField(default='TPM', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='full_name',
            field=models.CharField(default='Tam', max_length=50),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='full_name',
            field=models.CharField(default='Tam', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='TP Hồ Chí Minh', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default='2003-08-16'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(default='TPM', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Tam', max_length=50),
        ),
    ]
