# Generated by Django 5.0.4 on 2024-05-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0005_ministry_address_ministry_birthday_ministry_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
