# Generated by Django 5.0.4 on 2024-05-23 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0006_alter_lecturer_address_alter_lecturer_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='report_file',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
