# Generated by Django 5.0.4 on 2024-05-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0007_alter_thesis_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='students',
        ),
        migrations.AddField(
            model_name='thesis',
            name='lecturers',
            field=models.ManyToManyField(blank=True, null=True, through='theses.Instructor', to='theses.lecturer'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='theses.student'),
        ),
    ]
