# Generated by Django 5.0.4 on 2024-05-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0008_remove_thesis_students_thesis_lecturers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='lecturers',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
