# Generated by Django 5.0.4 on 2024-05-27 16:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0011_alter_thesis_council_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='theses.council'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='report_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='report_file'),
        ),
    ]
