# Generated by Django 5.0.4 on 2024-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0012_alter_thesis_council_alter_thesis_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='report_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
