# Generated by Django 5.0.4 on 2024-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0013_alter_thesis_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
