# Generated by Django 5.0.4 on 2024-05-30 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0017_remove_thesis_student_student_thesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('evaluation_method', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scorecolumn',
            name='score_component',
        ),
        migrations.RemoveField(
            model_name='scoredetail',
            name='score_column',
        ),
        migrations.RemoveField(
            model_name='scoredetail',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='score_number',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='council',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='score',
            name='criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theses.criteria'),
        ),
        migrations.CreateModel(
            name='ThesisCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.criteria')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.thesis')),
            ],
        ),
        migrations.DeleteModel(
            name='ScoreComponent',
        ),
        migrations.DeleteModel(
            name='ScoreColumn',
        ),
        migrations.DeleteModel(
            name='ScoreDetail',
        ),
    ]
