# Generated by Django 5.0.4 on 2024-05-30 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0018_criteria_remove_scorecolumn_score_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theses.criteria'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score_number',
            field=models.FloatField(),
        ),
    ]
