# Generated by Django 5.0.4 on 2024-05-30 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0021_remove_score_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='thesis',
        ),
        migrations.AddField(
            model_name='score',
            name='thesis_criteria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theses.thesiscriteria'),
        ),
    ]
